### ISSUE TITLE
Freeze on startup

### ISSUE THREAD

**Issue by SvenDaHacker64** [BernardoGiordano/Lasagna#2]
So, I opened this app, right after the "Homebrew" gameboot screen, it gets stuck with only red horizontal bars on top & bottom screens. I waited for like 10 mins and nothing comes up.

![win_20180120_11_44_46_pro](https://user-images.githubusercontent.com/29345291/35183042-6db82140-fdd7-11e7-9c90-fbb80841b6d3.jpg)

**Comment by Orionsilver** [comment]
reinstall the app

**Comment by SvenDaHacker64** [comment]
@Orionsilver Still doesn't work. I also tried with QR Code thing. Same issue with 3DSX too.

**Comment by BernardoGiordano** [comment]
Are you sure you really have titles in your 3ds?

**Comment by SvenDaHacker64** [comment]
Nevermind, the real problem was caused by some custom font. I re-installed original font and it works normally.
