### ISSUE TITLE
[Request] Download from 3DSMods!

### ISSUE THREAD

**Issue by ghost** [BernardoGiordano/Lasagna#7]
Is there any way that you could build this so that it connects to https://3dsmods.fm1337.com/ like how FBI connects to TitleDB

**Comment by hqppyz** [comment]
That site may need to provide an api in order to be added to the homebrew, but it's up to the developer anyway

**Comment by BernardoGiordano** [comment]
This has already been discussed with 3DSMods device and it's not going to be implemented from both sides
